name: commit-message-check

on: [push, pull_request]

jobs:
  commit-message-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run commit message validation with Bash script
        run: ./scripts/validate_commit_message.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
